CREATE TABLE  IF NOT EXISTS categories(id SERIAL PRIMARY KEY,name VARCHAR(50));
CREATE TABLE  IF NOT EXISTS products(id SERIAL PRIMARY KEY,name VARCHAR(50),price FLOAT,category_id INTEGER REFERENCES categories(id));
CREATE TABLE  IF NOT EXISTS users(id SERIAL PRIMARY KEY,first_name VARCHAR(50),last_name VARCHAR(50),password TEXT);
CREATE TABLE  IF NOT EXISTS orders(id SERIAL PRIMARY KEY,product_id INTEGER  REFERENCES products(id),quantity INTEGER , user_id INTEGER REFERENCES users(id),status BOOLEAN);